name:                numsort
version:             0.1.0.0
github:              "aha0x0x/numsort"
license:             BSD3
author:              "Abdul Hannan Ahsan"
maintainer:          "abdulhannan.ahsan@gmail.com"
copyright:           "2018 Abdul Hannan Ahsan"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/aha0x0x/numsort#readme>

dependencies:
- base >= 4.8 && < 5
- criterion >= 1.3.0.0
- clock >= 0.7.2
- formatting >= 6.3.4
- random >= 1.1

library:
  source-dirs: src

executables:
  numsort-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -O2
    dependencies:
    - numsort

tests:
  numsort-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - numsort
